services: 
  # docker run -d --name web1 --net mynetwork jmalloc/echo-server
  web:
    image: jmalloc/echo-server


  haproxy:
    container_name: haproxy
    image: haproxytech/haproxy-alpine:2.4
    volumes: 
      - "./config:/usr/local/etc/haproxy:ro"
    ports:
      - "80:80"
    depends_on: 
      - web

